mex -v sfunc_FOG.c createHandle.c
mex -v sfunc_RW_TX.c% createHandle.c
mex -v sfunc_RW_RX.c% createHandle.c
mex -v sfunc_GAS.c% createHandle.c
mex -v sfunc_MTQ.c% createHandle.c
mex -v sfunc_STT.c% createHandle.c
mex -v sfunc_NSAS.c% createHandle.c
mex -v sfunc_GPS.c% createHandle.c
%mex -v sfunc_GAS_HILS.c NIDAQmx.lib